networks:
  social-media:
    driver: bridge
services:
  app:
    container_name: social-media_web
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - social-media
    depends_on:
      - social-media_db
  social-media_db:
    container_name: social_media
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: social_media
    ports:
      - "5432:5432"
    networks:
      - social-media
    volumes:
      - postgres-data:/var/lib/postgresql/data
  citus_master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: "citusdata/citus:12.0.0"
    ports: [ "${COORDINATOR_EXTERNAL_PORT:-35432}:5432" ]
    labels: [ "com.citusdata.role=Master" ]
    environment: &AUTH
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGUSER: "${POSTGRES_USER:-postgres}"
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
  citus_worker:
    image: "citusdata/citus:12.0.0"
    labels: [ "com.citusdata.role=Worker" ]
    depends_on: [ citus_master ]
    environment: *AUTH
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - social-media
  post_creation_service:
    container_name: post_creation_service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: ./WebSocketService.PostCreation/Dockerfile
    ports:
      - 88:80
    networks:
      - social-media
    depends_on:
      - rabbitmq
volumes:
  postgres-data: